### ISSUE TITLE
[New issue]: fedbiomed_run node delete not working

### ISSUE THREAD

**Issue by ErwanDemairy** [fedbiomed/fedbiomed#851]
Dear user, welcome to the Fed-BioMed project ! We will get back to you as soon as possible.

When testing feature/810-add-documentation-to-declearn-optimizers, seems impossible to remove an existing node with the command delete:
```bash
$ ./scripts/fedbiomed_run node delete                
2023-09-06 16:01:31,129 fedbiomed DEBUG - Reading default biprime file "biprime0.json"


   __         _ _     _                          _                   _
  / _|       | | |   (_)                        | |                 | |
 | |_ ___  __| | |__  _  ___  _ __ ___   ___  __| |  _ __   ___   __| | ___
 |  _/ _ \/ _` | '_ \| |/ _ \| '_ ` _ \ / _ \/ _` | | '_ \ / _ \ / _` |/ _ \
 | ||  __/ (_| | |_) | | (_) | | | | | |  __/ (_| | | | | | (_) | (_| |  __/
 |_| \___|\__,_|_.__/|_|\___/|_| |_| |_|\___|\__,_| |_| |_|\___/ \__,_|\___|



	- 🆔 Your node ID: node_626dd395-d947-4681-b3bc-fafffd339aec 

Select the dataset to delete:
1) MNIST
@Select: 1
Traceback (most recent call last):
  File "/Users/edemairy/Developpement/fedbiomed/fedbiomed/node/cli_utils/_database.py", line 233, in delete_database
    dataset_manager.remove_database(tags)
  File "/Users/edemairy/Developpement/fedbiomed/fedbiomed/node/dataset_manager.py", line 537, in remove_database
    doc_ids = [doc.doc_id for doc in self.search_by_tags(tags)]
  File "/Users/edemairy/Developpement/fedbiomed/fedbiomed/node/dataset_manager.py", line 537, in <listcomp>
    doc_ids = [doc.doc_id for doc in self.search_by_tags(tags)]
AttributeError: 'dict' object has no attribute 'doc_id'
```

**Comment by mvesin** [comment]
Thanks @ErwanDemairy for reporting.
This is a regression introduced by #847
We will fix that next week.

**Comment by mvesin** [comment]
Fixed with #855
